package slimeknights.sconstruct.port1211.world.client;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

/**
 * Pinned-behaviour tests for the client-side slime renderer assets. The
 * {@link net.neoforged.neoforge.client.event.EntityRenderersEvent} pipeline can't be fired
 * here without a live client {@code EntityRendererProvider.Context} — those are wired by
 * {@link slimeknights.sconstruct.port1211.world.TinkerWorldPulse#register} guarded by
 * {@code Dist.CLIENT} and exercised at runtime — but the texture assets the renderers point
 * at can be probed against the test classpath, the same way other resource-presence tests
 * do for fluid sprites and slime block textures.
 */
class WorldEntityRenderersTest {

    @Test
    void blueslimeAndHugeslimeTexturesAreOnTheClasspath() {
        // Drift here means the renderer would fall back to the missing-texture sprite for the
        // entire entity — the AC's "No 'missing renderer' warnings" requires the entity-side
        // (renderer registered) and the asset-side (PNG packaged) both hold. The PNGs are
        // generated by the SMTCON-57 commit's PIL script from the legacy slime entity texture.
        ClassLoader cl = Thread.currentThread().getContextClassLoader();
        String blueslime = "assets/sconstruct/textures/entity/slime/blueslime.png";
        String hugeslime = "assets/sconstruct/textures/entity/slime/hugeslime.png";
        assertAll(() -> assertTrue(cl.getResource(blueslime) != null, blueslime + " missing"), () -> assertTrue(cl.getResource(hugeslime) != null, hugeslime + " missing"));
    }
}
