package slimeknights.sconstruct.shared;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.registries.DeferredBlock;

import org.junit.jupiter.api.Test;

import slimeknights.sconstruct.SConstruct;

/**
 * Pinned-behaviour tests for {@link SharedBlocks}. Verifies the storage-block coverage matches
 * the legacy precedent (every metal in {@link SharedMetals#ALL} except lead and nickel), every
 * field is non-null and namespaced under {@link SConstruct#MOD_ID sconstruct}, and the
 * exposed {@link SharedBlocks#METAL_BLOCKS} map is consistent with the static fields.
 */
class SharedBlocksTest {

    private static final List<String> EXPECTED_BLOCK_IDS = List.of("cobalt", "ardite", "manyullyn", "knightslime", "pigiron", "silver", "copper", "tin", "zinc", "brass", "alubrass", "electrum",
            "steel");

    @Test
    void registersOneStorageBlockPerMetalExceptTheSkippedTwo() {
        // Every metal in SharedMetals.ALL minus lead+nickel should have a registered storage
        // block. If a new metal is appended to SharedMetals and the author forgets to add a
        // field here, this fails.
        Set<String> expected = SharedMetals.ALL.stream().map(Metal::id).filter(id -> !SharedBlocks.skippedIds().contains(id)).collect(Collectors.toCollection(java.util.LinkedHashSet::new));
        assertEquals(expected, SharedBlocks.METAL_BLOCKS.keySet());
    }

    @Test
    void blockIdsAreNamespacedAndPrefixedConsistently() {
        // Storage blocks use the "block_<metal>" path so they don't collide with future ingot
        // items registered against the same metal id. Drift here would break tag JSONs and
        // recipe references generated by Phase-2 providers.
        assertAll(SharedBlocks.METAL_BLOCKS.entrySet().stream().map(entry -> () -> {
            DeferredBlock<Block> deferred = entry.getValue();
            assertEquals(SConstruct.MOD_ID, deferred.getId().getNamespace(), entry.getKey());
            assertEquals("block_" + entry.getKey(), deferred.getId().getPath(), entry.getKey());
        }));
    }

    @Test
    void declaredOrderMatchesLegacyExpectation() {
        // METAL_BLOCKS is a LinkedHashMap-backed view; downstream providers rely on insertion
        // order for deterministic generated artifacts (lang keys, recipe ids).
        assertEquals(EXPECTED_BLOCK_IDS, List.copyOf(SharedBlocks.METAL_BLOCKS.keySet()));
    }

    @Test
    void leadAndNickelAreSkipped() {
        // Pinned explicitly so a future refactor that "fills in" lead/nickel storage blocks
        // (a tempting consistency win, but it would invent content the legacy mod never had)
        // trips this test instead of slipping into a release.
        assertAll(() -> assertFalse(SharedBlocks.METAL_BLOCKS.containsKey("lead")), () -> assertFalse(SharedBlocks.METAL_BLOCKS.containsKey("nickel")),
                () -> assertTrue(SharedBlocks.skippedIds().contains("lead")), () -> assertTrue(SharedBlocks.skippedIds().contains("nickel")));
    }

    @Test
    void everyDeferredBlockFieldIsNonNullAndKeyedConsistently() {
        // Defends against a refactor that nulls out a public field — the map view would
        // technically still expose every metal, but downstream code reaching for
        // SharedBlocks.COBALT would NPE. Pin both shapes.
        Map<String, DeferredBlock<Block>> fields = Map.ofEntries(Map.entry("cobalt", SharedBlocks.COBALT), Map.entry("ardite", SharedBlocks.ARDITE), Map.entry("manyullyn", SharedBlocks.MANYULLYN),
                Map.entry("knightslime", SharedBlocks.KNIGHTSLIME), Map.entry("pigiron", SharedBlocks.PIGIRON), Map.entry("silver", SharedBlocks.SILVER), Map.entry("copper", SharedBlocks.COPPER),
                Map.entry("tin", SharedBlocks.TIN), Map.entry("zinc", SharedBlocks.ZINC), Map.entry("brass", SharedBlocks.BRASS), Map.entry("alubrass", SharedBlocks.ALUBRASS),
                Map.entry("electrum", SharedBlocks.ELECTRUM), Map.entry("steel", SharedBlocks.STEEL));
        assertAll(fields.entrySet().stream().map(entry -> () -> {
            assertNotNull(entry.getValue(), entry.getKey() + " field");
            assertEquals(SharedBlocks.METAL_BLOCKS.get(entry.getKey()), entry.getValue(), entry.getKey() + " map ↔ field consistency");
        }));
    }

    @Test
    void glowIsRegisteredAtLightLevel15() {
        // GLOW must light its surroundings — Phase-6 gadget recipes depend on it functioning as
        // a placeable light source. Pinning the level at the driver here catches a
        // copy/paste that would silently turn glow into a dark block.
        assertNotNull(SharedBlocks.GLOW);
        assertEquals(SConstruct.MOD_ID, SharedBlocks.GLOW.getId().getNamespace());
        assertEquals("glow", SharedBlocks.GLOW.getId().getPath());
        assertEquals(15, SharedBlocks.GLOW.get().defaultBlockState().getLightEmission());
    }

    @Test
    void firewoodAndLavawoodAreRegisteredWithMatchingShapeButDifferentHardness() {
        // Two blocks that share sound + light emission but differ on hardness per AC. The
        // tightest pin: same sound, same self-glow, lavawood strictly harder than firewood.
        assertNotNull(SharedBlocks.FIREWOOD);
        assertNotNull(SharedBlocks.LAVAWOOD);
        assertEquals("firewood", SharedBlocks.FIREWOOD.getId().getPath());
        assertEquals("lavawood", SharedBlocks.LAVAWOOD.getId().getPath());
        assertEquals(8, SharedBlocks.FIREWOOD.get().defaultBlockState().getLightEmission());
        assertEquals(8, SharedBlocks.LAVAWOOD.get().defaultBlockState().getLightEmission());
        float firewoodHardness = SharedBlocks.FIREWOOD.get().defaultDestroyTime();
        float lavawoodHardness = SharedBlocks.LAVAWOOD.get().defaultDestroyTime();
        org.junit.jupiter.api.Assertions.assertTrue(lavawoodHardness > firewoodHardness, "lavawood (" + lavawoodHardness + ") should be harder than firewood (" + firewoodHardness + ")");
    }

    @Test
    void decorativeBlocksAreNotInTheMetalBlocksMap() {
        // METAL_BLOCKS is the iteration surface downstream metal providers consume. Decorative
        // blocks must NOT leak into it or they'll get the metal-tier tag, the c:ingots/... tag
        // search, etc.
        assertAll(() -> assertFalse(SharedBlocks.METAL_BLOCKS.containsKey("glow")), () -> assertFalse(SharedBlocks.METAL_BLOCKS.containsKey("firewood")),
                () -> assertFalse(SharedBlocks.METAL_BLOCKS.containsKey("lavawood")));
    }
}
